

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BBLFood
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Entities17045_DB : DbContext
{
    public Entities17045_DB()
        : base("name=Entities17045_DB")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<jelo> jeloes { get; set; }

    public virtual DbSet<racun_jelo> racun_jelo { get; set; }

    public virtual DbSet<radno_mjesto> radno_mjesto { get; set; }

    public virtual DbSet<rezervacija> rezervacijas { get; set; }

    public virtual DbSet<zaposlenik> zaposleniks { get; set; }

    public virtual DbSet<jelovnik> jelovniks { get; set; }

    public virtual DbSet<jelovnik_jelo> jelovnik_jelo { get; set; }

    public virtual DbSet<sastojak> sastojaks { get; set; }

    public virtual DbSet<racun> racuns { get; set; }

    public virtual DbSet<zalihe> zalihes { get; set; }

}

}

