
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BBLFood
{

using System;
    using System.Collections.Generic;
    
public partial class rezervacija
{

    public int id { get; set; }

    public string ime_narucitelj { get; set; }

    public string prezime_narucitelj { get; set; }

    public string kontakt_broj_narucitelj { get; set; }

    public Nullable<int> id_zaposlenik { get; set; }

    public Nullable<int> broj_stola { get; set; }

    public string objed { get; set; }

    public Nullable<System.DateTime> datum { get; set; }

    public Nullable<int> broj_osoba { get; set; }

    public Nullable<System.TimeSpan> termin { get; set; }



    public virtual zaposlenik zaposlenik { get; set; }

}

}
