
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BBLFood
{

using System;
    using System.Collections.Generic;
    
public partial class sastojak
{

    public int id { get; set; }

    public string naziv { get; set; }

    public Nullable<decimal> kolicina { get; set; }

    public string mjerna_jedinica { get; set; }

    public Nullable<int> id_jelo { get; set; }

    public Nullable<int> id_zalihe { get; set; }



    public virtual jelo jelo { get; set; }

    public virtual zalihe zalihe { get; set; }

}

}
