
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BBLFood
{

using System;
    using System.Collections.Generic;
    
public partial class zalihe
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public zalihe()
    {

        this.sastojaks = new HashSet<sastojak>();

    }


    public int id { get; set; }

    public string naziv { get; set; }

    public Nullable<decimal> kolicina { get; set; }

    public string mjernaJedinica { get; set; }

    public Nullable<decimal> kriticna_kolicina { get; set; }

    public string datum { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<sastojak> sastojaks { get; set; }

}

}
